# Generated by Django 6.0 on 2025-12-09 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('harassment', 'Harassment'), ('financial', 'Financial'), ('mental', 'Mental Health'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('suggestion', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
